# Generated by Django 4.1.7 on 2023-06-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_image')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('review', models.IntegerField()),
                ('page', models.IntegerField()),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='female', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.FileField(upload_to='user_image'),
        ),
    ]
