# Generated by Django 4.1.7 on 2023-06-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='histroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('quntity', models.IntegerField()),
                ('rent_date', models.DateField()),
                ('return_data', models.DateField(null=True)),
                ('isRenew', models.BooleanField()),
                ('pyment', models.BigIntegerField()),
                ('pyment_Mode', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
