# Generated by Django 4.1.7 on 2023-06-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_histroy_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histroy',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.book'),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.users'),
        ),
    ]
