# Generated by Django 4.1.7 on 2023-06-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_histroy_book_id_alter_histroy_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histroy',
            name='book_id',
        ),
    ]
