# Generated by Django 4.1.7 on 2023-06-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_histroy_book_id_alter_histroy_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histroy',
            name='book_id',
        ),
    ]
